### ISSUE TITLE
Use incorrect compare operator for in-bound validation

### ISSUE THREAD

**Issue by safe4u** [h33p/cglue#17] opened 2024-07-07 04:31 UTC
We have found unsound problems caused by naive mistakes both in [`insert`](https://github.com/h33p/cglue/blob/main/cglue/src/vec.rs#L100) and [`remove`](https://github.com/h33p/cglue/blob/main/cglue/src/vec.rs#L127).

The `assert!` macros for in-bound validation incorrectly use '>' instead of '<'. 

## POC
Here follows a simple POC:
```rust
use cglue::vec::CVec;
fn main() {
    let a: Vec<u32> = vec![1, 2, 3];
    let mut cvec = CVec::from(a);
    cvec.insert(1, 2);
    cvec.remove(1);
    println!("cvec: {:?}", cvec);
}
```

**Comment by h33p** [comment] 2024-07-24 19:03
Thank you so much for reporting this! The issue is now fixed.

**Closed as completed** 2024-07-24 19:02 UTC
